[package]
name = "std-shims"
version = "1.0.0"
edition.workspace = true
license.workspace = true
description = "Standard library shims for `no_std` compatibility"

[features]
default = ["std"]
std = []
