[package]
name = "stwo_ml_verifier"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.54.0" }
cairo_test = "2.12.2"

[[target.starknet-contract]]
casm = true

[tool.snforge]
name = "stwo_ml_verifier"
