[package]
name = "obelysk_ml_air"
version = "0.1.0"
edition = "2024_07"

[lib]
casm = true

[dependencies]
stwo_verifier_core = { path = "../verifier_core" }
stwo_constraint_framework = { path = "../constraint_framework" }
stwo_verifier_utils = { path = "../verifier_utils" }
bounded_int = { path = "../bounded_int" }

[dev-dependencies]
cairo_test = "2.12.2"

[features]
default = []
poseidon252_verifier = ["stwo_verifier_core/poseidon252_verifier"]
